### ISSUE TITLE
`lein figwheel` fails 

### ISSUE THREAD

**Issue by shrmrf** [kendru/learn-cljs#1]
First of all thank you for this repository and the tutorial. _And sorry for the vague title for this issue. Today's the 3rd day of my Clojurescript journey and unfortunately I'm not very familiar with the Java ecosystem._

`lein figwheel` fails for me in the `lesson-10` and `lesson-9` programs. 

`lein version`:
```console
$ lein version
Leiningen 2.9.1 on Java 11.0.4 OpenJDK 64-Bit Server VM
```

Here's the error for `lesson-10`:
```console
$ lein figwheel
... other logs (looks fine till here ...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray, compiling:(clojure/core/rrb_vector/rrbt.clj:282:1)
```

I suspect this might have to do with the version of Leiningen+Java that I'm using??

**Comment by kendru** [comment]
Thanks for the report! I just updated the ClojureScript version for those projects, so it should be working now. The issue was that they were using an outdated version of ClojureScript the relied on a Java package that had been deprecated.
