### ISSUE TITLE
Lesson 7: Using a REPL for browser interaction

### ISSUE THREAD

**Issue by diop** [kendru/learn-cljs#40]
I tried to submit a pull request but lesson 7 seems to be missing from the repo.

In the section `Using a REPL for browser interaction` the directive for running `$ npm install` is missing. It might be confusing for a newcomer, because without it the namespaced REPL will not fire up.

Current:
```
$ lein new figwheel repl-explore
$ cd repl-explore
$ lein figwheel
```

Fix
```
$ lein new figwheel repl-explore
$ cd repl-explore
$ npm install
$ lein figwheel
```

Same is valid for Lesson 6 I believe with `reagent`, but I'll open another issue.

**Comment by kendru** [comment]
Thank you! There have been some changes with figwheel, and I will revise these chapters soon (or potentially switch to figwheel-main or shadow-cljs).
