### ISSUE TITLE
Can't preorder/donate from outside of US

### ISSUE THREAD

**Issue by fvkluck** [kendru/learn-cljs#43]
Hi,

First of all, thanks for writing this book. I really like the combination of hands-on writing code and setting stuff up on the one hand, and on the other hand the theoretical background in why clojurescript is a good choice.
I have never worked with javascript, but I feel this gives me the power to understand/lookup what I need to know.

So I wanted to pre-order the book, more with the goal of supporting the project than to receive the actual copy, but I found out that's only possible with an address in the US. I'd be happy to pay the same amount for a preorder of a future epub release if you're planning that. Or just as a donation if you're planning to keep the website open (which would be a great help also for people with smaller budgets).

Best,
Florian

**Comment by kendru** [comment]
The book is now available internationally, and I am working on an ebook now!
