### ISSUE TITLE
Lesson 14: clj command to create new project returns "No function found on command line or in :exec-fn"

### ISSUE THREAD

**Issue by alvinsim** [kendru/learn-cljs#49]
I am following the tutorial on "Lesson 14: Performing I/O" and the `clj` command that is used to create a new project doesn't work for me. Below is a snippet of the command and error message returned.

`$ clj -X:new :template figwheel-main :name doing-io :args '["+deps"]'
No function found on command line or in :exec-fn`

Is there something that I have missed before this step?

Below are the details of my development environment:
- Clojure version: 1.10.2
- OS: Debian (10.8) running on WSL2

**Comment by alvinsim** [comment]
My bad. I see it now on "Lesson 5"

**Comment by zaynmalik2611** [comment]
I am having the same error what should i do?

**Comment by alexsukhrin** [comment]
The answer is in lesson 5

**Comment by Flinner** [comment]
check `~/.config/clojure/deps.edn`  instead of `~/.clojure/deps.edn`.
