### ISSUE TITLE
Book: listing 8.6 is missing % sign

### ISSUE THREAD

**Issue by rogererens** [kendru/learn-cljs#53]
In the book in section 8.2 on page 80, the (-> ) macro is missing the %-sign between -> and .-target.

**Comment by rogererens** [comment]
Same type of issue for listing 10.9, which also has "\circled{6}" in the text.

**Comment by kendru** [comment]
Thanks! I have made the changes in the LaTeX source, and they will be in the book if I do a second printing :)
