### ISSUE TITLE
`make-contact` function needs fix

### ISSUE THREAD

**Issue by MityaDementiy** [kendru/learn-cljs#81]
Hi, @kendru!
I worked with [Contact Book capstone project](https://github.com/kendru/learn-cljs/blob/main/content/section-3/lesson-20-capstone-3-contact-book.md) and noticed the problem. When I use this code:
```clojure
(defn maybe-set-address [contact]                          ;; <1>
  (if (:address contact)
    (update contact :address make-address)
    contact))

(defn make-contact [contact]
  (-> contact                                              ;; <2>
      (select-keys [:first-name :last-name :email])
      (maybe-set-address)))
```
`make-contact` function returns contact without `:address` field. I assume it should be fixed in this way:

```clojure
(defn make-contact [contact]
  (-> contact
      (select-keys [:first-name :last-name :email :address])
      (maybe-set-address)))
```
Thank you for this great book!

**Comment by kendru** [comment]
Thank you so much for the fixes!
